---
# tasks file for application_evtx_move_zip_delete.yml
#
# ==========================================================================
# move application evtx files from default location to c:\temp
# ==========================================================================
- name: "move application evtx files from default location to c:\\temp"
  win_shell: >
    gci -path {{ windows_default_log_path }} Archive-application*.evtx
    -recurse | move-item -destination c:\temp;test-path -path
    c:\temp\Archive-application*.evtx
  register: move_app_files
  ignore_errors: true

- name: "set output variable"
  set_fact:
   move_app_files_out: "{{ move_app_files.stdout_lines|list|join }}"

- debug:
   msg: >
    "Any errors with the move will be listed here........
    {{ move_app_files_out }}"

# ==========================================================================
# zip up application evtx files & store in eventlogs folder
# ==========================================================================
- name: "Zip up application evtx files & store in eventlogs Folder"
  win_shell: >
    cd\;cd {{ eventlogs_path_out }};get-location;
    {{ zip_path }} a -tzip application_{{ date_out }}.zip
    c:\temp\Archive-Se*.*
  register: zip_app_evtx
  ignore_errors: true

- name: "set output variable"
  set_fact:
   zip_app_evtx_out: "{{ zip_app_evtx.stdout_lines|list|join }}"

- debug:
   msg: >
    "Any Zip application log output will be listed here........
    {{ zip_app_evtx_out }}"

# ==========================================================================
# Delete application evtx files in the c:\temp folder
# ==========================================================================
- name: "Delete application evtx files in the c:\temp folder"
  win_shell: >
    Remove-Item -path c:\temp\Archive-application*.evtx -force
  register: del_app_evtx
  ignore_errors: true

- name: "set output variable"
  set_fact:
   del_app_evtx_out: "{{ del_app_evtx.stdout_lines|list|join }}"

- debug:
   msg: >
    "Any Delete application log output will be listed here........
    {{ del_app_evtx_out }}"
